#!/bin/bash
set -euo pipefail

# End-to-end PRS workflow:
#   Step 0  prepare_prs_weights.py  derive SNP weights from GWAS logistic results
#   Step 1  plink --score           compute per-sample polygenic risk scores
#   Step 2  merge_prs_pheno.py      join scores to phenotype; write summary table
#   Step 3  plot_prs.py             histogram and case/control boxplot
#
# Usage:
#   bash scripts/run_prs.sh <GENO_PREFIX> <PHENO_FILE> <GWAS_FILE> <OUT_PREFIX> [P_THRESHOLD]
#
# Arguments:
#   GENO_PREFIX    PLINK1 binary prefix (path without .bed/.bim/.fam extension)
#   PHENO_FILE     Tab- or comma-separated file with IID and PHENO columns
#   GWAS_FILE      PLINK .assoc.logistic file (CHR SNP BP A1 TEST NMISS OR STAT P)
#   OUT_PREFIX     Output prefix; all result files are written as <OUT_PREFIX>_*
#   P_THRESHOLD    Optional. P-value threshold for selecting GWAS variants (default: 0.05)
#
# Example:
#   cd 07_polygenic_risk_score
#   bash scripts/run_prs.sh \
#     ../05_population_pca/results/demo_genotypes_qc \
#     ../06_asthma_gwas/results/asthma_pheno.txt \
#     ../06_asthma_gwas/results/asthma_gwas.assoc.logistic \
#     results/asthma_prs

# ---- Working directory guard ----
if [[ ! -f "scripts/run_prs.sh" ]]; then
    echo "Error: run this script from the 07_polygenic_risk_score/ directory."
    echo "  cd 07_polygenic_risk_score && bash scripts/run_prs.sh ..."
    exit 1
fi

# ---- Dependency check ----
if ! command -v plink &>/dev/null; then
    echo "Error: 'plink' not found in PATH."
    echo "  conda activate genomics_pipeline"
    echo "  (on macOS arm64: conda install -c bioconda plink)"
    exit 1
fi

# ---- Argument check ----
if [[ $# -lt 4 ]] || [[ $# -gt 5 ]]; then
    echo "Usage: bash scripts/run_prs.sh <GENO_PREFIX> <PHENO_FILE> <GWAS_FILE> <OUT_PREFIX> [P_THRESHOLD]"
    echo ""
    echo "  GENO_PREFIX    PLINK1 binary prefix (without extension)"
    echo "  PHENO_FILE     TSV/CSV with IID and PHENO columns"
    echo "  GWAS_FILE      PLINK .assoc.logistic file (CHR SNP BP A1 TEST NMISS OR STAT P)"
    echo "  OUT_PREFIX     Output prefix for all generated files"
    echo "  P_THRESHOLD    P-value cutoff for variant selection (default: 0.05)"
    echo ""
    echo "Example:"
    echo "  bash scripts/run_prs.sh \\"
    echo "    ../05_population_pca/results/demo_genotypes_qc \\"
    echo "    ../06_asthma_gwas/results/asthma_pheno.txt \\"
    echo "    ../06_asthma_gwas/results/asthma_gwas.assoc.logistic \\"
    echo "    results/asthma_prs"
    exit 1
fi

GENO_PREFIX="$1"
PHENO_FILE="$2"
GWAS_FILE="$3"
OUT_PREFIX="$4"
P_THRESHOLD="${5:-0.5}"

# Weights file is generated by Step 0; consumed by Step 1
WEIGHTS_FILE="${OUT_PREFIX}_weights.tsv"

# ---- Input validation ----
for ext in bed bim fam; do
    if [[ ! -f "${GENO_PREFIX}.${ext}" ]]; then
        echo "Error: genotype file not found: ${GENO_PREFIX}.${ext}"
        exit 1
    fi
done

if [[ ! -f "$PHENO_FILE" ]]; then
    echo "Error: phenotype file not found: $PHENO_FILE"
    exit 1
fi

if [[ ! -f "$GWAS_FILE" ]]; then
    echo "Error: GWAS association file not found: $GWAS_FILE"
    exit 1
fi

# ---- Create output directories ----
OUT_DIR=$(dirname "$OUT_PREFIX")
mkdir -p "$OUT_DIR" results/figures

echo "=== PRS Workflow ==="
echo "  Genotypes   : $GENO_PREFIX"
echo "  Phenotype   : $PHENO_FILE"
echo "  GWAS file   : $GWAS_FILE"
echo "  P threshold : $P_THRESHOLD"
echo "  Output      : $OUT_PREFIX"
echo ""

# ---- Step 0: Derive PRS weights from GWAS results ----
echo "Step 0: Preparing PRS weights from GWAS results..."
python scripts/prepare_prs_weights.py \
    --gwas         "$GWAS_FILE" \
    --out          "$WEIGHTS_FILE" \
    --p-threshold  "$P_THRESHOLD"
echo "  -> $WEIGHTS_FILE"
echo ""

# ---- Step 1: Score with PLINK 1.9 ----
# Column positions in the weight file: 1=SNP, 2=A1, 3=BETA
# 'header' tells PLINK the first line is a header, not a variant record
# Output: <OUT_PREFIX>.profile  (FID IID PHENO CNT CNT2 SCORE)
echo "Step 1: Running plink --score..."
plink \
    --bfile "$GENO_PREFIX" \
    --score "$WEIGHTS_FILE" 1 2 3 header \
    --out   "$OUT_PREFIX"
echo "  -> ${OUT_PREFIX}.profile"
echo ""

# ---- Step 2: Merge scores with phenotype ----
echo "Step 2: Merging PRS with phenotype..."
python scripts/merge_prs_pheno.py \
    --sscore "${OUT_PREFIX}.profile" \
    --pheno  "$PHENO_FILE" \
    --out    "${OUT_PREFIX}_merged.tsv"
echo ""

# ---- Step 3: Plot ----
echo "Step 3: Generating plots..."
python scripts/plot_prs.py \
    --merged  "${OUT_PREFIX}_merged.tsv" \
    --out-dir results/figures \
    --prefix "$(basename "$OUT_PREFIX")"
echo ""

echo "=== Done ==="
echo "Outputs:"
echo "  $WEIGHTS_FILE                  PLINK2 score file (SNP A1 BETA)"
echo "  ${OUT_PREFIX}_weights_summary.tsv  variants used + GWAS stats"
echo "  ${OUT_PREFIX}.profile              raw PLINK 1.9 per-sample scores"
echo "  ${OUT_PREFIX}_merged.tsv           scores merged with phenotype"
echo "  ${OUT_PREFIX}_summary.tsv          per-group summary statistics"
echo "  results/figures/prs_histogram.png"
echo "  results/figures/prs_boxplot.png    (only if phenotype groups present)"
